### PR TITLE
Add aarch64 support

### PR DESCRIPTION
**Pull request by kczulko**
This PR improves the situation for multiplatform build. It does not bring full range of platforms (dropped macos/darwin support) but adds aarch64/x86_64/mingwW64 ones.

Nix was used to provide the whole environment and linkers. Also, github actions were slightly modified to reuse new nix-based environment provisioning. However, if someone doesn't want to use nix, there's still the ability to build things "manually" (installing `rust`, running `gradlew` or `asdf`). Therefore `compileRust` gradle action contains conditional expression that differentiates build/nix env from the "native" one.

This setup doesn't fully use nix-based rust provisioning. Instead of complete purity, rust env is provisioned via rustup (through the `shellHook`).

This PR and github actions were tested on my fork:
- https://github.com/kczulko?tab=packages&repo_name=substrate-client-java
- https://github.com/kczulko/substrate-client-java/actions/runs/8246605540/job/22552973845

Also we've tested those artifacts on our dev envs. All *.so files were correctly loaded:
```
03-12 11:21:57.675 Info Native: OS detected: linux
03-12 11:21:57.675 Info Native: jni_crypto source path: /include/aarch64-linux/libjni_crypto.so
03-12 11:21:57.695 Info Native: jni_crypto temp dir: /tmp/jni_crypto_lib13950631278669393069
03-12 11:21:57.729 Info Native: jni_crypto load path: /tmp/jni_crypto_lib13950631278669393069/libjni_crypto.so
```

### CODE REVIEW

**Review by pfrank13 — CHANGES_REQUESTED** [review]
Doesn't build out for macOS Intel or Linux amd64 with `gradlew clean build`

**Review by pfrank13 — CHANGES_REQUESTED** [review]
So I've gone over the changes and without support either for maven qualifiers to publish jars on a per os/arch basis or by including all native builds in a single jar and changing the classpath at runtime then we can't accept this. The crux of the issue is we only have 1 set of maven co-ordinates and we are not on aarch yet so we need x86 support and aarch support simultaneously, qualifiers can solve this but so can the other approach of including support for all native types in a single jar (this is how https://github.com/splix/polkaj) works.

I think the path of least resistance is this fork publishes to it's own artifact repository under your control and you folks can pick up from there. The most "correct" way IMO is the polkaj approach. The compromise is maven qualifier style publishing. That latter 2 options being much more lift than the former.

If you think I'm in error please send me a built jar that is working on aarch from your side and I'll try and run it locally on my Linux box (which is not aarch) and see if it bombs, I suspect it will.

**Comment by kczulko** [comment]
@pfrank13 

Here's the fork where we've published the jars that contains supported architectures: https://github.com/sgrouples/substrate-client-java. In this case we have a single `crypto` jar containing dynamic libraries for: x86_64-linux, aarch64-linux, windows. The structure of such jar resources looks like that:
```
...
  -rw-r--r--     1945  12-Mar-2024 09:40:08  com/strategyobject/substrateclient/crypto/KeyPair.class
  -rw-r--r--     1227  12-Mar-2024 09:40:08  com/strategyobject/substrateclient/crypto/SecretKey.class
  -rw-r--r--     1243  12-Mar-2024 09:40:08  com/strategyobject/substrateclient/crypto/SignatureData.class
  drwxr-xr-x        0  12-Mar-2024 09:40:06  include/
  drwxr-xr-x        0  12-Mar-2024 09:40:06  include/x86_64-linux/
  -rwxr-xr-x  4039096  12-Mar-2024 09:40:06  include/x86_64-linux/libjni_crypto.so
  drwxr-xr-x        0  12-Mar-2024 09:40:06  include/windows/
  -rwxr-xr-x  5843588  12-Mar-2024 09:40:06  include/windows/jni_crypto.dll
  drwxr-xr-x        0  12-Mar-2024 09:40:06  include/aarch64-linux/
  -rwxr-xr-x  4194960  12-Mar-2024 09:40:06  include/aarch64-linux/libjni_crypto.so
```

**Review by pfrank13 — APPROVED** [review]
Thanks @kczulko for enlightening me, my ingorance knows no bounds! This is a fantastic change to the project. Thanks so much for the contribution!

**Pull request merged**
